import os
# game
FPS = 60
WIN_WIDTH = 800
WIN_HEIGHT = 600
DISPLAY = (WIN_WIDTH, WIN_HEIGHT)
BACKGROUND_COLOR = "#000000"
SCREEN_START = (0, 0)
FILE_DIR = os.path.dirname(__file__)
# monsters
MONSTER_WIDTH, MONSTER_HEIGHT, MONSTER_COLOR = 32, 32, '#2111FF'
ICON_DIR_MONSTER = os.path.dirname(__file__)
# block
PLATFORM_WIDTH, PLATFORM_HEIGHT, PLATFORM_COLOR = 32, 32, '#000000'
ICON_DIR_PLATFORM = os.path.dirname(__file__)
# PLAYER
MOVE_SPEED = 7
MAVE_EXTRA_SPEED = 2.5
WIDTH, HEIGHT, COLOR = 22, 32, '#888888'
JUMP_POWER, JUMP_EXTRA_POWER, GRAVITY = 10, 1, 0.25
ANIMATION_DELAY, ANIMATION_SUPER_SPEED_DELAY = 0.1, 0.05

ICON_DIR_PLAYER = os.path.dirname(__file__)
ANIMATION_RIGHT = [ICON_DIR_PLAYER]
ANIMATION_LEFT = [ICON_DIR_PLAYER]
ANIMATION_JUMP = [ICON_DIR_PLAYER]
ANIMATION_JUMP_RIGHT = [ICON_DIR_PLAYER]
ANIMATION_JUMP_LEFT = [ICON_DIR_PLAYER]
ANIMATION_STAY = [ICON_DIR_PLAYER]
